module.exports = {
    br: 'br1',
    eune: 'eun1',
    euw: "euw1",
    jp: 'jp1',
    kr: 'kr',
    lan: 'la1',
    las: 'la2',
    na: 'na1',
    oce: 'oc1',
    tr: 'tr1',
    ru: 'ru',
    pbe: 'pbe1',
    br1: 'br',
    eun1: 'eune',
    euw1: 'euw',
    jp1: 'jp',
    kr: 'kr',
    la1: 'las',
    la2: 'lan',
    na1: 'na',
    oc1: 'oce',
    tr1: 'tr',
    ru: 'ru',
    pbe1: 'pbe'
}
